[package]
name = "scu"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.3", features = ["derive"] }
home = "0.5.5"
serde = { version = "1.0.164", features = ["derive"] }
toml = "0.7.4"
